### PR TITLE
Run tests on multiple node versions in travis

### PR DESCRIPTION
**Pull request by sudo-suhas**
The tests can run in parallel and the module can be used with confidence on the tested node versions.

### CODE REVIEW

**Comment by asfktz** [comment]
Waited for you to put your hands of that file 😉

I'm new to CI,  so feel free to change it however you believe is necessary.

**Comment by sudo-suhas** [comment]
> Waited for you to put your hands of that file :wink: 

Ha ha.. too much.

Here is a sample `.travis.yml` file - https://github.com/sudo-suhas/elastic-builder/blob/master/.travis.yml

I dunno how good it is though.. I started working on open source recently too.
Couple of things we can do:
- Cache `node_modules`. This can improve build times
- Add rule to not test branches created by `npm version` or `yarn version`. 

As of now you are not using [greenkeeper](https://greenkeeper.io/) or a hosted service for coverage. While greenkeeper might be overkill right now, I can highly recommend https://coveralls.io/.

Let's discuss here before I make the PR for travis config change.

**Comment by sudo-suhas** [comment]
Actually none of these changes are needed per se. The current one will serve the purpose just fine.

**Comment by asfktz** [comment]
Yeah, I guess time will tell us what we need (:

**Pull request merged**
