### PR TITLE
add prettier, husky, and lint-staged

### PR DESCRIPTION
**Pull request by viankakrisna**

### CODE REVIEW

**Comment by sudo-suhas** [comment]
Looks like `yarn.lock` was not updated. And the `lint-staged` config does not run `eslint --fix`. Also I prefer [`eslint-plugin-prettier`](https://github.com/prettier/eslint-plugin-prettier). Formatting, linting can be done through `eslint` itself.

**Comment by asfktz** [comment]
Thanks you for the PR @viankakrisna,
I decided to merge #18 for now.

I believe it will be wiser to add prettier in a PR of its own.

**Comment by sudo-suhas** [comment]
@asfktz Would be simpler if you set it up to avoid conflicts. The repo is being updated quite frequently as of now. You could also customise it to your preference.

**Comment by asfktz** [comment]
Ok, I will.

**Pull request closed without merging**
