### PR TITLE
docs(readme): Tweaks readme grammar

### PR DESCRIPTION
**Pull request by d3viant0ne**
Looking forward to giving this a test run this weekend.

- Small update to the readme with a few grammatical tweaks.

As an aside, you should really consider an RFC in webpack/webpack to land this functionality in core.

### CODE REVIEW

**Comment by asfktz** [comment]
Hi @d3viant0ne, thanks!
That is so kind of you (:

**Comment by d3viant0ne** [comment]
`RFC` === `Request for Comment` in other words an issue representing a Proposal to have a feature or improvement added to Webpack.

Example = `https://github.com/webpack/webpack/issues/4499`

**Comment by asfktz** [comment]
Oh, nice!
Yeah, thats a good idea, I'll do it.

**Comment by d3viant0ne** [comment]
No problem, I'll get a pull request open some time this week to make the switch over there.

**Pull request merged**
