### PR TITLE
Propagate process exit code in integration test script

### PR DESCRIPTION
**Pull request by sudo-suhas**
I noticed that even though the integration test failed, the pre-commit hook did not fail. The status code returned by the child process was not being propagated. So this PR does the following:
- If any tests(right now only 'basic') fail, the script exits with exit code 1.
- Adds some logging.
- Makes the script and helpers node 4 compatible. Since we wouldn't be developing on node 4, testing it on CI is a good idea.
- Tweak travis config:
  - Test on node 4, 9.
  - Stop testing on node 7.

### CODE REVIEW

**Comment by sudo-suhas** [comment]
Tests are still failing on node 4 because it is unable to find some modules. This happens because npm@2 does not flatten installed modules and node is not able to find some packages which would be nested deeply in the project root's `node_modules`. 

We could do any of the following to fix the issue:
- As part of the install step on travis, also install modules in integration test fixtures.
- Run `npm install` before `npm test` in test script.
- Install a newer version of npm on node 4 so that `node_modules` are flattened. 🡠 _I like this one_

**Comment by asfktz** [comment]
> We could do any of the following to fix the issue:
>
> * As part of the install step on travis, also install modules in integration test fixtures.
> * Run npm install before npm test in test script.
> * Install a newer version of npm on node 4 so that node_modules are flattened. 🡠 I like this one

What are the downsides of the first option?

**Comment by sudo-suhas** [comment]
The installation step would need to `cd` into each folder in `specs/fixtures` and run install. The CI config would need to be updated each time we add an integration test. However, the current approach might fail if the integration test has a dependency not installed in the project root.

**Comment by asfktz** [comment]
Hmmm.. if I understands correctly, sound like it can be automated by adding the installing step to `./scripts/runIntegrationTests.js`:
https://github.com/asfktz/autodll-webpack-plugin/blob/78ca76539443e41249a7b369c0fcb5be35a4c394/scripts/runIntegrationTests.js#L1-L18


Something like:

```js
readdirSync(cwd)
  .filter(isDirectory)
  .map(dirname => join(cwd, dirname))
  .forEach(ctx => {
    spawnSync('npm', ['install'], {
      cwd: ctx,
      shell: true,
      stdio: 'inherit',
    });
  })
  .forEach(ctx => {
    spawnSync('npm', ['test'], {
      cwd: ctx,
      shell: true,
      stdio: 'inherit',
    });
  });
```

Will it do the trick?

**Comment by sudo-suhas** [comment]
Yea, that was option 2. I'll update the PR to that instead.

**Comment by asfktz** [comment]
Ohh sorry, I missed that

**Comment by sudo-suhas** [comment]
No problem 😃

**Comment by sudo-suhas** [comment]
This is why the tests are still failing on node 4:

```
λ cd specs\fixtures\basic\

λ node
> require.resolve('write-pkg')
'E:\\Projects\\repos\\autodll-webpack-plugin\\specs\\fixtures\\basic\\node_modules\\write-pkg\\index.js'
> .exit

λ cd ..\..\helpers\integration\

λ node
> require.resolve('write-pkg')
'E:\\Projects\\repos\\autodll-webpack-plugin\\node_modules\\write-pkg\\index.js'
```

The package resolution for integration tests helpers will be up the directory tree which does not include `specs/fixtures/basic`. While the installation step is still useful, our issue is not yet resolved. That leaves us with 2 options:
- Move the helpers inside `specs/fixtures/basic`. This would mean that we won't be able to share them between integration tests, if and when we have multiple.
- Use `npm@3` on node v4. This approach isn't guaranteed to succeed as it is somewhat a coincidence that `write-pkg` is a transient dependency:
  ```
  λ yarn why write-pkg
  yarn why v1.3.2
  [1/4] Why do we have the module "write-pkg"...?
  [2/4] Initialising dependency graph...
  [3/4] Finding dependency...
  [4/4] Calculating file sizes...
  info This module exists because "ava#ava-init" depends on it.
  Done in 1.33s.
  ```
- Add the packages required by integration test helpers to our dev-deps. 🡠 _I like this one_

**Comment by sudo-suhas** [comment]
I went with the third option.

I have added the installation step as a separate script. The rationale for this is that in our development environment, if we want to run integration tests, we shouldn't have to run `npm install`(it is particularly buggy on windows). I'd much rather manage that manually. Plus, we can simply do `npm run install:fixturedeps` if needed.

**Comment by asfktz** [comment]
I see.
Let's go with that 👍

**Pull request merged**
