### PR TITLE
Minor typo corrections to readme documentation

### PR DESCRIPTION
**Pull request by sudo-suhas**
This corrects a few typos and fixes some grammatical errors.

### CODE REVIEW

**Comment by sudo-suhas** [comment]
You should consider merging this with a ['Rebase and merge'](https://help.github.com/articles/about-pull-request-merges/#rebase-and-merge-your-pull-request-commits). This will not create a merge commit. I feel merge commits add a bit of noise for minor change commits such as these.

**Comment by sudo-suhas** [comment]
Hey @asfktz, is there anything you'd like me to change in this? The build failure is unrelated. Only the readme file was modified.

**Comment by asfktz** [comment]
@sudo-suhas,
Sorry I haven't replied yet. I have really busy days lately.

Thanks for the PR. I really appreciate it.

It looks good, there's only one thing.

This was not a typo:

```js
new AutoDllPlugin({
  context: path.join(__dirname, '..'),
  entry: [
    'react',
    'react-dom'
    './src/module.js'
  ]
})
```

I wanted the entry option to be more aligned with webpack's entry.
So I used this example, but unfortunately, I haven't found the time to support it yet.

So it's better to be:
```js
new AutoDllPlugin({
  context: path.join(__dirname, '..'),
  entry: {
    vendor: [
      'react',
      'react-dom',
      './src/module.js'
    ]
  }
})
```

Other than that it looks great!

**Comment by sudo-suhas** [comment]
@asfktz No issues. 

> This was not a typo:

I found it a little odd because `src` file was being pulled into `vendor` bundle. I'll revert this no worries.

**Comment by asfktz** [comment]
Merged. Thanks @sudo-suhas (:

**Pull request merged**
