### PR TITLE
Support extra plugins in config (such as UglifyJS)

### PR DESCRIPTION
**Pull request by drewhamlett**

### CODE REVIEW

**Comment by d3viant0ne** [comment]
Why try to optimize a dev only DLL?

**Comment by drewhamlett** [comment]
The way we are currently using DLL is speed up dev times as well as compile times on platforms such as Heroku.  We update our production vendor as well as dev vendor locally.  We went from 2 minute builds to 20 seconds, something that Common Chunks and Happy Pack couldn't come close too.

**Comment by d3viant0ne** [comment]
Interesting, I can't say I would have thought of that from a devops perspective :)

**Comment by cpsubrian** [comment]
Hate to just +1 something, but I have a similar use case. I'd like to commit my production DLL to reduce the processing time of Netlify's continuous deployment pipeline. We trigger redeploys from CMS webhooks so they happen a lot, and the faster the better.

**Comment by dlong500** [comment]
@d3viant0ne I don't see any reason why the `DllPlugin` can't be used in production.  Can anyone point out downsides?  Especially in the context of this autodll project it would be great to get a simplified way to split code for both dev and production scenarios.

In fact, I could see this plugin as a starting point for wrapping other more complex scenarios covering `CommonsChunkPlugin` and dynamic imports as well.

**Comment by asfktz** [comment]
Thanks for the PR, @drewhamlett!
This is definitely a feature worth adding.

It looks good! I would like to double check it before I merge it.

Interesting, I always thought about DLLs as a development tool, but it does make sense.

whether or not it's a good practice, adding an option to pass plugins to the DLL Compiler config is a good idea.


> Especially in the context of this autodll project it would be great to get a simplified way to split code for both dev and production scenarios.

I agree, @dlong500, the plugin should not be too opinionated about its use cases.

**Comment by cpsubrian** [comment]
Another option, rather than accepting `plugins` specifically, would be to allow passing a `config` object and just merge that in using [webpack-merge](https://github.com/survivejs/webpack-merge). Then uses could pass plugins (or anything else) (or even override default config).

**Comment by d3viant0ne** [comment]
@dlong500 - I never said or suggested you couldn't or shouldn't. I had just personally never thought to do it.

All of my applications are containerized, the use case @drewhamlett outlined above isn't something I have ever run into which is why I asked about it.

**Comment by sudo-suhas** [comment]
Any idea what would be the implications of trying to use it for both dev **&** prod?

**Comment by dlong500** [comment]
The only issue I can see with production usage is if you were also using stuff like dynamic imports.  I don't believe the `DllPlugin` architecture handles dynamic imports like `CommonsChunkPlugin` does.  Ultimately I'd like to see a plugin that could start with what `CommonsChunkPlugin` can do now (including handling dynamic imports) and add all the `DllPlugin` features as well.  Combine that with an easy configuration along with cache handling like this project does and I think that would be great for both dev and production.

**Comment by sudo-suhas** [comment]
The bundle generated for dev and prod would be different right? If there is already cached bundle for dev, when I run prod build, will it overwrite? Should the user perhaps tweak his config so the bundles don't conflicT?

**Comment by dlong500** [comment]
You may be right.  I'm realizing the plugin may not invalidate the cache if the only thing that changed was NODE_ENV.  It might make sense to have a separate cache per NODE_ENV value.

As far as the bundles conflicting, that would be up to the developer to set proper actions based on NODE_ENV, but I think the bigger issue is making sure it doesn't use cached data generated under a different NODE_ENV.

**Comment by sudo-suhas** [comment]
Some notes could be added to readme addressing this. Needs some investigation to understand exact behavior too.

**Comment by viankakrisna** [comment]
the cache invalidation is too aggressive right now and not taking account of an outside of settings variables. It deletes all files in `cacheDir` if settings have been changed. I've opened https://github.com/asfktz/autodll-webpack-plugin/pull/13 for the first pass of using hash and additional files to watch for validating cache. Can do more in [getHash](https://github.com/viankakrisna/autodll-webpack-plugin/blob/27b267c204c0d732b1473d5db449dbd2ef778eee/src/compileIfNeeded.js#L66-L76),[storeHash](https://github.com/viankakrisna/autodll-webpack-plugin/blob/27b267c204c0d732b1473d5db449dbd2ef778eee/src/compileIfNeeded.js#L27-L29) and [cleanup](https://github.com/viankakrisna/autodll-webpack-plugin/blob/27b267c204c0d732b1473d5db449dbd2ef778eee/src/compileIfNeeded.js#L25)

**Pull request merged**
