### PR TITLE
Add eslint, eslint-plugin-react to devDependencies

### PR DESCRIPTION
**Pull request by sudo-suhas**
`eslint` recommends installing locally - http://eslint.org/docs/user-guide/getting-started
> If you want to include ESLint as part of your project’s build system, we recommend installing it locally.

This also allows to control the `eslint` version as well as install any required plugins for the project.

### CODE REVIEW

**Comment by sudo-suhas** [comment]
Incidentally, there are a few linting errors in the project:
```
λ .\node_modules\.bin\eslint.cmd src specs

E:\Projects\repos\autodll-webpack-plugin\src\compileIfNeeded.js
  53:1  error  Expected indentation of 8 spaces but found 10  indent
  54:1  error  Expected indentation of 8 spaces but found 10  indent
  55:1  error  Expected indentation of 8 spaces but found 10  indent
  56:1  error  Expected indentation of 8 spaces but found 10  indent
  57:1  error  Expected indentation of 6 spaces but found 10  indent
  58:1  error  Expected indentation of 8 spaces but found 10  indent

E:\Projects\repos\autodll-webpack-plugin\src\plugin.js
  38:11  warning  'log' is assigned a value but never used  no-unused-vars

E:\Projects\repos\autodll-webpack-plugin\specs\compileIfNeeded.spec.js
   51:1  error  Expected indentation of 4 spaces but found 2   indent
   52:1  error  Expected indentation of 4 spaces but found 2   indent
   53:1  error  Expected indentation of 6 spaces but found 4   indent
   55:1  error  Expected indentation of 6 spaces but found 4   indent
   56:1  error  Expected indentation of 6 spaces but found 4   indent
   57:1  error  Expected indentation of 4 spaces but found 2   indent
   88:1  error  Expected indentation of 8 spaces but found 6   indent
   89:1  error  Expected indentation of 10 spaces but found 8  indent
   90:1  error  Expected indentation of 8 spaces but found 6   indent
  100:1  error  Expected indentation of 8 spaces but found 6   indent
  101:1  error  Expected indentation of 10 spaces but found 8  indent
  102:1  error  Expected indentation of 8 spaces but found 6   indent

✖ 19 problems (18 errors, 1 warning)
  18 errors, 0 warnings potentially fixable with the `--fix` option.
```

Maybe you are using a different version of `eslint`? Or can I fix these issues and make a PR?

**Comment by asfktz** [comment]
Interesting, I used `eslint --init` to initialize the config. Always thought it adds `eslint` to `devDependencies` by itself.

About the warnings, I'll take care of it. 

Thanks!

**Comment by asfktz** [comment]
I believe the warnings should be gone now.

**Comment by sudo-suhas** [comment]
I usually add a couple of npm scripts and setup `pre-commit` with [`lint-staged`](https://github.com/okonet/lint-staged) so the stuff gets automatically checked before a commit.. 

I can make a PR with that if you are interested.

**Comment by asfktz** [comment]
That's a good idea.
Sure, I'd appreciate that.

**Pull request merged**
