### PR TITLE
Add [chunkhash] support (#101)

### LINKED ISSUE #101: No output file while using [chunkhash] in filename
There is no any output dll file in path I set while using [chunkhash] in filename
```javascript
new AutoDllPlugin({
  filename: '[name].[chunkhash].js',    // No output file in ./lib
  path: './lib',
  entry: {
    polyfill: ['core-js', 'regenerator-runtime'],
    react: ['react', 'react-dom'],
    moment: ['moment']
  }
})
```

But when I change [chunkhash] to [hash], it just work.

```javascript
new AutoDllPlugin({
  filename: '[name].[hash].js',    // output file emitted
  path: './lib',
  entry: {
    polyfill: ['core-js', 'regenerator-runtime'],
    react: ['react', 'react-dom'],
    moment: ['moment']
  }
})
```

My webpack version is 3.10.0 and autodll-webpack-plugin is 0.3.8.
Please help.

### PR DESCRIPTION
**Pull request by CJY0208**
Change `[name]_[hash]` to `[name]_[chunkhash]` in options given to `DllPlugin`.  
Closes #101

### CODE REVIEW

**Comment by CJY0208** [comment]
The output is not correct although passed the test. Close pull request and check again.

**Comment by sudo-suhas** [comment]
Thanks @CJY0208 and apologies for the delay in response.

**Comment by sudo-suhas** [comment]
ping @asfktz

**Comment by asfktz** [comment]
Hi @CJY0208,
Thank you for the PR and sorry for the long wait.
I released a new version with the fix.

**Pull request merged**
